from models_2 import quadratic, quadratic_err
calibration = lambda x : quadratic(x, 1.0712199169673612e-06,0.9983939332295696,14.612110926616722)
calibration_error = lambda x, x_err : quadratic_err(x,x_err,1.0712199169673612e-06,4.006605910164234e-08,0.9983939332295696,0.0003790105269935516,14.612110926616722,0.8590858568531958)
